### ISSUE TITLE
bel-enrichment cli out of sync with latest pybel version

### ISSUE THREAD

**Issue by djinnome** [bel-enrichment/bel-enrichment#7]
Hi @cthoyt 

When I try to run `bel-enrichment` from the command line with or without arguments, I get the following error. I presume this is because the latest version of pybel no longer has a `to_json_path()` method.

```python
bel-enrichment --help
Traceback (most recent call last):
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/bin/bel-enrichment", line 5, in <module>
    from bel_enrichment.cli import main
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/bel_enrichment/__init__.py", line 5, in <module>
    from .repository import BELSheetsRepository  # noqa: F401
  File "/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/bel_enrichment/repository.py", line 17, in <module>
    from pybel import BELGraph, from_pickle, to_json_path, to_pickle
ImportError: cannot import name 'to_json_path' from 'pybel' (/Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pybel/__init__.py)
```

**Comment by djinnome** [comment]
a  quick update.

I installed from the latest github and that seemed to get past the `to_json` issue. I still can't export a bel script, but I could export nodelink and as long as I supplied the magic *.bel.nodelink.json bel-enrichment was able to ingest the file. Now the block is that I haven't set the INDRA_DB_REST_URL yet (and presumably the INDRA_DB_REST_API_KEY). So I'll take care of that tomorrow at the meeting

**Comment by cthoyt** [comment]
Should be solved with new release at https://pypi.org/project/bel-enrichment/0.0.5/. Please close the issue if this solves your problem

(I realize i forgot to remove the text about the rest API keys. maybe you can test if they're really needed or not - should be not because John and Ben said)
